// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: api/process_order.proto

package bidirectional_streaming

import (
	context "context"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BidirectionalStreamingService_ProcessOrders_FullMethodName = "/bidirectional_streaming.BidirectionalStreamingService/processOrders"
)

// BidirectionalStreamingServiceClient is the client API for BidirectionalStreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BidirectionalStreamingServiceClient interface {
	ProcessOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[wrappers.StringValue, CombinedDelivery], error)
}

type bidirectionalStreamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBidirectionalStreamingServiceClient(cc grpc.ClientConnInterface) BidirectionalStreamingServiceClient {
	return &bidirectionalStreamingServiceClient{cc}
}

func (c *bidirectionalStreamingServiceClient) ProcessOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[wrappers.StringValue, CombinedDelivery], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BidirectionalStreamingService_ServiceDesc.Streams[0], BidirectionalStreamingService_ProcessOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[wrappers.StringValue, CombinedDelivery]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BidirectionalStreamingService_ProcessOrdersClient = grpc.BidiStreamingClient[wrappers.StringValue, CombinedDelivery]

// BidirectionalStreamingServiceServer is the server API for BidirectionalStreamingService service.
// All implementations must embed UnimplementedBidirectionalStreamingServiceServer
// for forward compatibility.
type BidirectionalStreamingServiceServer interface {
	ProcessOrders(grpc.BidiStreamingServer[wrappers.StringValue, CombinedDelivery]) error
	mustEmbedUnimplementedBidirectionalStreamingServiceServer()
}

// UnimplementedBidirectionalStreamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBidirectionalStreamingServiceServer struct{}

func (UnimplementedBidirectionalStreamingServiceServer) ProcessOrders(grpc.BidiStreamingServer[wrappers.StringValue, CombinedDelivery]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessOrders not implemented")
}
func (UnimplementedBidirectionalStreamingServiceServer) mustEmbedUnimplementedBidirectionalStreamingServiceServer() {
}
func (UnimplementedBidirectionalStreamingServiceServer) testEmbeddedByValue() {}

// UnsafeBidirectionalStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BidirectionalStreamingServiceServer will
// result in compilation errors.
type UnsafeBidirectionalStreamingServiceServer interface {
	mustEmbedUnimplementedBidirectionalStreamingServiceServer()
}

func RegisterBidirectionalStreamingServiceServer(s grpc.ServiceRegistrar, srv BidirectionalStreamingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBidirectionalStreamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BidirectionalStreamingService_ServiceDesc, srv)
}

func _BidirectionalStreamingService_ProcessOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BidirectionalStreamingServiceServer).ProcessOrders(&grpc.GenericServerStream[wrappers.StringValue, CombinedDelivery]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BidirectionalStreamingService_ProcessOrdersServer = grpc.BidiStreamingServer[wrappers.StringValue, CombinedDelivery]

// BidirectionalStreamingService_ServiceDesc is the grpc.ServiceDesc for BidirectionalStreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BidirectionalStreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bidirectional_streaming.BidirectionalStreamingService",
	HandlerType: (*BidirectionalStreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "processOrders",
			Handler:       _BidirectionalStreamingService_ProcessOrders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/process_order.proto",
}
